apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/tls/ca.pem
    server: https://__MASTER_IP__
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    user: default-admin
  name: local
current-context: local
kind: Config
preferences: {}
users:
- name: default-admin
  user:
    client-certificate: /etc/kubernetes/tls/admin.pem
    client-key: /etc/kubernetes/tls/admin-key.pem